// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTTxQ_ik60TLypO0Yk3oRA_c-mnCmKojk',
    appId: '1:46268110173:web:3412092de7e38653b104b4',
    messagingSenderId: '46268110173',
    projectId: 'student-task-manager-72ebe',
    authDomain: 'student-task-manager-72ebe.firebaseapp.com',
    storageBucket: 'student-task-manager-72ebe.firebasestorage.app',
    measurementId: 'G-4GPYL6SD6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6-BcldX1I2A0mSmgVnZoqXEfMFyvUupo',
    appId: '1:46268110173:android:5ae3b4bb12cd8740b104b4',
    messagingSenderId: '46268110173',
    projectId: 'student-task-manager-72ebe',
    storageBucket: 'student-task-manager-72ebe.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTTxQ_ik60TLypO0Yk3oRA_c-mnCmKojk',
    appId: '1:46268110173:web:bd0436cab7f2519bb104b4',
    messagingSenderId: '46268110173',
    projectId: 'student-task-manager-72ebe',
    authDomain: 'student-task-manager-72ebe.firebaseapp.com',
    storageBucket: 'student-task-manager-72ebe.firebasestorage.app',
    measurementId: 'G-HXWHXJ20D7',
  );
}
